apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-aws
  labels:
    app: deploy-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-aws
  template:
    metadata:
      labels:
        app: deploy-aws
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: "512Mi"
            cpu: "0.2"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

